# Generated by Django 3.2 on 2022-09-10 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_book_selling_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='selling_Price',
        ),
    ]
