# Generated by Django 3.2 on 2022-09-21 13:44

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_book_selling_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('book', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('order_status', models.CharField(choices=[('Order Completed', 'Order Completed'), ('Order Processing', 'Order Processing'), ('Order Canceled', 'Order Canceled'), ('On the way', 'On the way'), ('Order Received', 'Order Received')], default='Order Received', max_length=100)),
                ('date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
