# Generated by Django 3.2 on 2022-09-21 14:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='book',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=[], size=None),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Order Completed', 'Order Completed'), ('Order Processing', 'Order Processing'), ('On the way', 'On the way'), ('Order Canceled', 'Order Canceled'), ('Order Received', 'Order Received')], default='Order Received', max_length=100),
        ),
    ]
