# Generated by Django 3.2 on 2022-09-21 15:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20220921_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='book',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(blank=True, null=True), size=None),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Order Processing', 'Order Processing'), ('Order Received', 'Order Received'), ('Order Completed', 'Order Completed'), ('On the way', 'On the way'), ('Order Canceled', 'Order Canceled')], default='Order Received', max_length=100),
        ),
    ]
