# Generated by Django 3.2 on 2022-09-24 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20220921_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Order Received', 'Order Received'), ('On the way', 'On the way'), ('Order Canceled', 'Order Canceled'), ('Order Processing', 'Order Processing'), ('Order Completed', 'Order Completed')], default='Order Received', max_length=100),
        ),
    ]
