# Generated by Django 3.2 on 2022-10-07 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Order Canceled', 'Order Canceled'), ('On the way', 'On the way'), ('Order Processing', 'Order Processing'), ('Order Completed', 'Order Completed'), ('Order Received', 'Order Received')], default='Order Received', max_length=100),
        ),
    ]
