# Generated by Django 3.2 on 2022-09-17 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phoneOTP',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
